# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-13 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shazam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wavfiles',
            name='name',
            field=models.CharField(default=' ', max_length=80),
        ),
    ]
